### ISSUE TITLE
ERROR Installing [Consistency Changes to Game Dialogues], 

### ISSUE THREAD

**Issue by Lzw104522773** [Gibberlings3/Road_To_Discovery_for_SoD#25]
I installed "Jasteys_SoD_tweakpack" on BG1EE and EET, and then installed Road-To-Discoveryfor-SoD, but there is a prompt as follows:

Detected Jastey's Tweakpack "More Dialogue Choices & Prevent Dead Ends"。
Copying and patching 1 file ...
ERROR: No translation provided for @54
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Consistency Changes to Game Dialogues], rolling back to previous state
Will uninstall   9 files for [SODRTD/SODRTD.TP2] component 10.
Uninstalled      9 files for [SODRTD/SODRTD.TP2] component 10.
ERROR: Not_found
Please make a backup of the file: SETUP-SODRTD.DEBUG and look for support at: https://baldurs-gate.de/index.php?resources/road-to-discovery-for-sod.59/
Using Language [Simplified Chinese]

Install Component [Consistency Changes to Game Dialogues]?
[I]nstall, or [N]ot Install or [Q]uit?

I blocked the installation of "Consistency Changes to Game Dialogues" .

PS: replaced the Chinese in the weidu prompt with English.

**Comment by Gitjas** [comment]
> PS: replaced the Chinese in the weidu prompt with English.

I'm not sure what you meant with that, I guess you mean for the SoD tweakpack?
 RtD refers to one line in the tweak pack where I needed to do some extra fetching in case it's a language that's not present in both mods yet.
I think it's easiest if you provide the translation of the tweak pack for me to integrate, and then I can adjust RtD so it installs.

**Comment by Gitjas** [comment]
Er, like you already did. I hope I'll find time for a new release soon.

**Comment by Lzw104522773** [comment]
What I mean is that the "Consistency Changes to Game Dialogues" component in this mod cannot coexist with the "More Dialogue Choices&Prevent Dead Ends" component in Jasteys_SoD_tweakpack? Or is there a conflict?

**Comment by Gitjas** [comment]
No conflict per se, I only scrambled the language checks in RtD for the patching. The master branches of the two mods should work together now, I wont be able to release Releases before mid of July.

**Comment by Lzw104522773** [comment]
OK.
